#!/usr/bin/env sh

# Description:
#   Search for a word in OS X
#
# Author:
#   jonahoffline (Jonah Ruiz) <jonah@pixelhipsters.com>
#
# Github:
#   https://github.com/jonahoffline/shell_stuff

grep --color -i "$1" /usr/share/dict/words

